check chiitoitsu and kokushi musou in check_tenpai()
rasca0027/Mahjong4RL pull request #45
Opened 2020-10-11 23:00 UTC by ktc312

2020-10-15 01:22 UTC, ktc312 commented on mahjong/naki_and_actions.py
> +            every possible tile's index that could complete the hand
not index

2020-10-15 01:31 UTC, rasca0027 requested changes

2020-10-15 01:31 UTC, rasca0027 commented on mahjong/naki_and_actions.py
> +        if honor_tiles_n == 8:
重複的可能是么九牌！！

2020-10-15 01:31 UTC, ktc312 commented on mahjong/naki_and_actions.py
> +        for tile in honor_tiles:
規則搞錯惹，是全部的么九牌都至少一張，其中一個兩張

2020-10-16 15:55 UTC, rasca0027 approved these changes

2020-10-16 17:47 UTC, merged